services:
  mysql:
    image: mysql
    container_name: mysql_sobunsobun
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
  redis:
    image: redis
    container_name: redis_sobunsobun
    hostname: redis
    ports:
      - "6378:6379"
  mongo:
    image: mongo:6
    container_name: mongo_sobunsobun
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1231
    volumes:
      - mongo_data:/data/db
  mongo-express:
    image: mongo-express
    container_name: mongo_express_sobunsobun
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1231

volumes:
  mysql-data:
  mongo_data: